# Generated by Django 5.1.4 on 2025-01-23 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_assesment_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='accessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assesments', to='core.accessor'),
        ),
    ]
