# Generated by Django 5.1.4 on 2025-01-23 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_assesment_accessor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assesments', to='core.client'),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assesments', to='core.project'),
        ),
    ]
