# Generated by Django 5.1.4 on 2025-01-23 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_assesment_client_alter_assesment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='core.quote'),
        ),
    ]
