# Generated by Django 5.1.4 on 2025-01-23 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bid_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='core.job'),
        ),
    ]
