# Generated by Django 5.1.4 on 2025-01-24 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bid_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='accessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quote', to='core.accessor'),
        ),
    ]
