# Generated by Django 5.1.4 on 2025-01-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_quote_accessor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='accessor',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='preference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='building_type',
            field=models.CharField(choices=[('detached', 'Detached'), ('semi-detached', 'Semi-detached'), ('mid-terrace', 'Mid-terrace'), ('apartment', 'Apartment'), ('duplex', 'Duplex'), ('bunglow', 'Bunglow'), ('multi-unit', 'Multi-unit'), ('other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in Progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('accessor', 'Accessor')], default='client', max_length=255),
        ),
    ]
