# Generated by Django 5.1.4 on 2025-02-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_assesment_shower_1_flow_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='activation_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
