# Generated by Django 5.1.4 on 2025-02-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_usermodel_activation_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
