# Generated by Django 5.1.4 on 2025-02-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_usermodel_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='pin_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
